-- BUILD IN FUNCTIONS

SELECT LEN('Hello world') AS UZUNLUK
SELECT UPPER('test') AS BÜYÜKHARF
SELECT LOWER('Test') AS KÜÇÜKHARF
SELECT LEFT('Hello world' , 3) AS [SOLDAN 3]
SELECT RIGHT('Hello world' , 3) AS [SAÐDAN 3]
SELECT CONCAT('Hello', ' world') AS [BÝRLEÞTÝRME]
SELECT GETDATE() AS ÞÝMDÝ
SELECT DATEDIFF(DAY,'1998-12-17','2024-12-17')
SELECT DATEDIFF(MONTH,'1998-12-17','2024-12-17')
SELECT DATEDIFF(YEAR,'1998-12-17','2024-12-17')
SELECT SUBSTRING('HELLO WORLD',9,5)
SELECT DATEPART(YEAR, GETDATE())
SELECT ROUND(123.456,3)--SON RAKAMINA GÖRE '3'
SELECT CEILING(123.49)
SELECT FLOOR(123.51)
SELECT REPLACE('HELLO WORLD','HELLO','SELAM')
SELECT LTRIM('  MERHABA  ')
SELECT RTRIM('  MERHABA  ')
SELECT REPLICATE('ABC',3)
SELECT 'MERHABA' + SPACE(5)+ 'DUNYA'

--UDF - KULLANICI TANIMLI FONKSÝYONLAR

--3 ÇEÞÝT FONKSÝYON VARDIR
-- 1. SCALER DEÐERLÝ (TEK DEÐER DÖNEN)
-- 2. TABLO DÖNENLER
-- 3. ÇOK DEYÝMLÝ TABLO DÖNEN FONKSÝYONLAR

-- 1 SCALER

--DDLandDML_DB DOSYASI ÝLE ÇALIÞTIRILDI
CREATE FUNCTION HESAPLA(@Sayi1 FLOAT , @Sayi2 FLOAT)
RETURNS FLOAT 
AS 
BEGIN
RETURN(@Sayi1 * @Sayi2)
END
SELECT dbo.HESAPLA(11.0,10.3) AS SONUC

--Aþaðýda ki queryler northwind den almýþtýr
USE Northwind
GO
ALTER FUNCTION FN_FiyatArttýrma(@Fiyat FLOAT)
RETURNS FLOAT
AS
BEGIN
DECLARE @Deger FLOAT
SET @Deger = @Fiyat+5.10
RETURN @Deger
END

SELECT dbo.FN_FiyatArttýrma(10)
SELECT ProductName,UnitPrice,dbo.FN_FiyatArttýrma(UnitPrice) AS YENÝFÝYAT FROM Products

alter FUNCTION FN_KDVhesap(@Fiyat FLOAT, @KDV FLOAT)
RETURNS FLOAT
AS
BEGIN
DECLARE @ATAMA FLOAT
SET @ATAMA = @Fiyat+(@Fiyat * @KDV)
RETURN @ATAMA
END
SELECT UnitPrice,dbo.FN_KDVhesap(UnitPrice,0.18) as KDVli FROM Products
--ORDERS YEAR()

CREATE FUNCTION FN_SiparisHesap(@id INT,@Yil INT)
RETURNS INT
AS
BEGIN
RETURN (SELECT COUNT(OrderID) FROM Orders WHERE EmployeeID= @id and YEAR(OrderDate)=@Yil)
END
SELECT dbo.FN_SiparisHesap(2,1996)

ALTER FUNCTION FN_SiparisHesap(@id NCHAR(10), @ilkTarih DATE, @sonTarih DATE)
RETURNS MONEY
AS
BEGIN
    RETURN (
        SELECT SUM(OD.UnitPrice * OD.Quantity * (1 - OD.Discount))
        FROM Customers C
        JOIN Orders O ON C.CustomerID = O.CustomerID
        JOIN [Order Details] OD ON O.OrderID = OD.OrderID
        WHERE O.OrderDate BETWEEN @ilkTarih AND @sonTarih
          AND C.CustomerID = @id
    )
END


SELECT dbo.FN_SiparisHesap('ANTON', '1997-01-13', '1997-06-30') AS ToplamTutar;


--CASE WHEN ÖRNEÐÝ

CREATE FUNCTION FN_AY_BUL
(@AyNO TINYINT)
RETURNS VARCHAR(20)
AS
BEGIN
RETURN
(
SELECT CASE @AyNO
	WHEN 1 THEN 'OCAK'
	WHEN 2 THEN 'ÞUBAT'
	WHEN 3 THEN 'MART'
	WHEN 4 THEN 'NÝSAN'
	WHEN 5 THEN 'MAYIS'
	WHEN 6 THEN 'HAZÝRAN'
	WHEN 7 THEN 'TEMMUZ'
	WHEN 8 THEN 'AÐUSTOS'
	WHEN 9 THEN 'EYLÜL'
	WHEN 10 THEN 'EKÝM'
	WHEN 11 THEN 'KASIM'
	WHEN 12 THEN 'ARALIK'
	ELSE 'TANIMSIZ'
END
)
END

SELECT dbo.FN_AY_BUL(6)
